name: lbd-sun-hc

on:
  push:
    branches:
      - main

jobs:
  lbd-on-sun-hc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update File
      run: |
        echo "on-sun-hc" > data.txt
        git config --global user.email "2zbgnk@gmail.com"
        git config --global user.name "LaMaCourses"
        git add data.txt
        git commit -m "Mise Ã  jour du fichier"

        git push https://LaMaCourses:LABADENQUET2_SECRET@github.com/LaMaCourses/Labadenquet     
      env:
        GITHUB_TOKEN: ${{ secrets.LABADENQUET2_SECRET }}
